version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:iam::654654295123:role/codedeploy_ecs   "
        LoadBalancerInfo:
          ContainerName: "swiggy"
          ContainerPort: 3000
