version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: shivakumar
    DOCKER_REGISTRY_PASSWORD: dornala
    DOCKER_REGISTRY_URL: docker.io
    SONAR_TOKEN: sqp_c33af976ad9e7be3104f14d40a32c7d6b9352edd
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - echo "Performing Trivy file scan before building the image..."
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
 # post_build:
 #    commands:
 #      - aws ses send-email --from "madithati123@gmail.com" --to "shivakumar200320@gmail.com" --subject "CodeBuild Status: $CODEBUILD_BUILD_ID" --text "Build status: $CODEBUILD_BUILD_STATUS" --region "ap-south-1"



artifacts:
  files:
    - appspec.yaml
